### ISSUE TITLE
Consider a CLI name change?

### ISSUE THREAD

**Issue by bobmaerten** [ivantsepp/annotate_gem#2]
Hello.

First I'd like to congratulate on you gem idea, as I manually comment gems additions in my Gemfiles.
But you should consider a name change for the command-line tool as `grub` is a popular boot loader on Linux systems, and may result on confusion for linux rubists.

**Comment by ivantsepp** [comment]
Thanks for using the gem! Yea I've heard that feedback from several people now. I can definitely change the command line to be something else like `grub-it` or something. Do you think would suffice for clearing the confusion? Or should the project be renamed as well?

**Comment by jakeonrails** [comment]
I did not know of this gem until Ruby Weekly today, and a couple of days ago I released `annotate_gemfile` which does nearly the same thing.

I'd be happy to give up the name of that gem if you want to use it.

**Comment by DexterTheDragon** [comment]
GRUB uses a number of grub- named commands so I wouldn't suggest it.
```
grub-editenv          grub-menulst2cfg      grub-mkpasswd-pbkdf2  grub-render-label   
grub-file             grub-mkconfig         grub-mkrelpath        grub-script-check   
grub-fstest           grub-mkdevicemap      grub-mkrescue         grub-set-default    
grub-glue-efi         grub-mkfont           grub-mkstandalone     grub-syslinux2cfg   
grub-install          grub-mkimage          grub-mount                                
grub-kbdcomp          grub-mklayout         grub-probe                                
grub-macbless         grub-mknetdir         grub-reboot
```

**Comment by ivantsepp** [comment]
@jakeonrails Oh wow, what a coincidence! Great minds think alike 😉. We should collaborate since we're thinking of the same goals 😄 

It looks like `grub` is not a good name and I think we should rename this project and the cli. I really like `annotate` (how come I didn't think of this before!) but I'm not sure about `gemfile` part since for https://github.com/ivantsepp/grub/issues/1, I see a use case of doing a similar thing with the `gemspec`. Perhaps `annotate_gems`?

**Comment by jakeonrails** [comment]
`annotate_gems` sounds good. I already forked your project and I'm brewing a little tweak to cause the comments to word wrap at 80 characters so that long gem descriptions don't ride off into the horizon.

**Comment by vassilevsky** [comment]
JFYI `annotate` is a good old gem for annotating models 🙃

**Comment by bramswenson** [comment]
I have to agree, grub is one of the most common linux packages known. It is the bootloader used on most linux distributions. The original grub package is so commonly used this grub would surface only on the most specific searches. It even has a wikipedia page: https://en.wikipedia.org/wiki/GNU_GRUB

Great project idea, not such a great name choice. You should strongly consider a name change of this project.

**Comment by ivantsepp** [comment]
@jakeonrails That's a great idea! I eagerly wait for a PR if you want to get it merged 😄, it would be cool if that was also configurable, allowing people to specify what they want the column width limit to be.

Thanks for all the feedback everyone. I've gone ahead and renamed the project to `annotate_gem`! See https://rubygems.org/gems/annotate_gem and https://github.com/ivantsepp/annotate_gem. 

I apologize to people who already forked the project under the old name `grub`. However, updating the remove url should be simple! You should be able to use `git remote set-url origin new_url` to set it to the new name.
