### ISSUE TITLE
hello nice gem

### ISSUE THREAD

**Issue by MadBomber** [ivantsepp/annotate_gem#5]
This is not an issue.  Just a hello.  I did not see your eMail address in your profile.  Just found out about your gem through RubyWeekly newsletter.  Nicely done sir.  I also like the herokuapp you put together for it as well.

I had the same idea a while ago, but kept it to myself.  I chose to put the comments inline.  I felt that it made the Gemfile less cluttered and more easily read.

Mine was just a quick and dirty get it done thing.  Here is my source in case you might consider changing the location of the comment to inline.

https://github.com/MadBomber/scripts/blob/master/comment_gemfile

Dewayne
  o-*

**Comment by ivantsepp** [comment]
@MadBomber Oh wow, great minds think alike 😉 . 

I really like the idea of putting comments inline! I'm thinking we could make it an option - allow users to choose between "above the gem line" or "inline". Thanks for the idea! I'll ping back in this issue once that's in place 😄

**Comment by ivantsepp** [comment]
Finally got around to adding an option to add these comments inline. Thanks for your suggestion!

I didn't add any logic about lining up those comments neatly but we can address in another issue/PR 😄
