### ISSUE TITLE
Has trouble with non-ASCII character in old version of Nokogiri

### ISSUE THREAD

**Issue by agrimm** [ivantsepp/annotate_gem#7]
Given a Gemfile of

    gem 'nokogiri', '1.5.11'
    gem 'annotate_gem', '~> 0.0.11'

The annotation has nonsensical letters instead of 鋸 (the kanji for nokogiri). I got

    # Nokogiri (é¸) is an HTML, XML, SAX, and Reader parser (http://nokogiri.org)

It works fine with nokogiri 1.6.0 .

Ruby version:

    ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]

Gemfile.lock:

    GEM
      specs:
        annotate_gem (0.0.11)
          bundler (~> 1.1)
        nokogiri (1.5.11)

    PLATFORMS
      ruby

    DEPENDENCIES
      annotate_gem (~> 0.0.11)
      nokogiri (= 1.5.11)

    BUNDLED WITH
       1.14.3

This might be an error in Nokogiri rather than annotate_gem: https://rubygems.org/gems/nokogiri/versions/1.5.11 also has a broken version of the character, while https://rubygems.org/gems/nokogiri/versions/1.6.0.rc1 is non-broken.

https://rubygems.org/gems/nokogiri/versions/1.5.1 has a non-broken character, while https://rubygems.org/gems/nokogiri/versions/1.5.2 has a broken character.

**Comment by ivantsepp** [comment]
Very interesting! Would love if anyone knew more about this to explain the behavior. But you can broken character in https://rubygems.org/gems/nokogiri/versions/1.5.11 but not https://rubygems.org/gems/nokogiri/versions/1.6.0.rc1. So seems like not an issue with this gem.
